/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import java.io.*;
import java.lang.reflect.Array;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author System Manager
 */
public class AdminAddSport extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddSport
     */
    public AdminAddSport() {
        initComponents();
        updateRadioButton();
    }
    
    private void updateRadioButton(){
        buttonGroup1.clearSelection();
        try {
            BufferedReader br = new BufferedReader(new FileReader("Sport Records.txt"));
            KualaLumpurRadio.setEnabled(true);
            SelangorRadio.setEnabled(true);
            SabahRadio.setEnabled(true);
            KedahRadio.setEnabled(true);
            SarawakRadio.setEnabled(true);
            String temp;
            String[] data;
            String sportName = SportNameComboBox.getSelectedItem().toString();
            while ((temp = br.readLine()) != null) {
                data = temp.split("\t", -1);
                if (data[1].equals(sportName)){
                    try {
                        BufferedReader cbr = new BufferedReader(new FileReader("Sport Centers.txt"));
                        String[] cdata;
                        while ((temp = cbr.readLine()) != null) {
                            cdata = temp.split("\t", -1);
                            if (cdata[0].equals(data[2])) {
                                if (cdata[0].equals("SC001")) {
                                    KualaLumpurRadio.setEnabled(false);
                                    KualaLumpurRadio.setSelected(false);
                                }
                                if (cdata[0].equals("SC002")) {
                                    SelangorRadio.setEnabled(false);
                                    SelangorRadio.setSelected(false);
                                }
                                if (cdata[0].equals("SC003")) {
                                    SabahRadio.setEnabled(false);
                                    SabahRadio.setSelected(false);
                                }
                                if (cdata[0].equals("SC004")) {
                                    KedahRadio.setEnabled(false);
                                    KedahRadio.setSelected(false);
                                }
                                if (cdata[0].equals("SC005")) {
                                    SarawakRadio.setEnabled(false);
                                    SarawakRadio.setSelected(false);
                                }
                            }
                        }
                        cbr.close();
                    } 
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }
            br.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    
    private String getSportCenterID(String name) {
        try {
            BufferedReader br = new BufferedReader(new FileReader("Sport Centers.txt"));
            String temp;
            String[] data;
            while ((temp = br.readLine()) != null) {
                data = temp.split("\t", -1);
                if (name.equals(data[1])){
                    return data[0];
                }
            }
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        return "MISSING";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AdminAddSportLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        SportCenterLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        KualaLumpurRadio = new javax.swing.JRadioButton();
        SelangorRadio = new javax.swing.JRadioButton();
        SabahRadio = new javax.swing.JRadioButton();
        SarawakRadio = new javax.swing.JRadioButton();
        KedahRadio = new javax.swing.JRadioButton();
        SportNameComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 600));

        AdminAddSportLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AdminAddSportLabel.setText("Add Sport Record");

        NameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        NameLabel.setText("Name:");

        SportCenterLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportCenterLabel.setText("Available Sport Center:");

        AddButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(KualaLumpurRadio);
        KualaLumpurRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KualaLumpurRadio.setText("Kuala Lumpur");

        buttonGroup1.add(SelangorRadio);
        SelangorRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SelangorRadio.setText("Selangor");
        SelangorRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelangorRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(SabahRadio);
        SabahRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SabahRadio.setText("Sabah");

        buttonGroup1.add(SarawakRadio);
        SarawakRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SarawakRadio.setText("Sarawak");

        buttonGroup1.add(KedahRadio);
        KedahRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KedahRadio.setText("Kedah");

        SportNameComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SportNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Football", "Archery", "Gymnastics", "Volleyball", "Basketball", "Cricket", "Tennis", "Table Tennis" }));
        SportNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportNameComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KualaLumpurRadio)
                        .addGap(18, 18, 18)
                        .addComponent(SelangorRadio)
                        .addGap(18, 18, 18)
                        .addComponent(SabahRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SportCenterLabel)
                            .addComponent(NameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SportNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KedahRadio)
                        .addGap(18, 18, 18)
                        .addComponent(SarawakRadio))
                    .addComponent(AdminAddSportLabel))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(AdminAddSportLabel)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SportNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SportCenterLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KualaLumpurRadio)
                    .addComponent(SelangorRadio)
                    .addComponent(SabahRadio))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SarawakRadio)
                    .addComponent(KedahRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminAddRecord aar = new AdminAddRecord();
        aar.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SelangorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelangorRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelangorRadioActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if (buttonGroup1.getSelection() == null){
            JOptionPane.showMessageDialog(this, "Please choose a sport center.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            try{
                BufferedReader br = new BufferedReader(new FileReader("Sport Records.txt"));
                int line = 0;
                while (br.readLine() != null){
                    line++;
                }
                line++;
                String sportID = "SP" + String.format("%03d", line);
                String sportName = SportNameComboBox.getSelectedItem().toString();
                String sportCenterID;
                if (KualaLumpurRadio.isSelected()){
                    sportCenterID = getSportCenterID("Kuala Lumpur");
                }
                else if (SelangorRadio.isSelected()){
                    sportCenterID = getSportCenterID("Selangor");
                }
                else if (SabahRadio.isSelected()){
                    sportCenterID = getSportCenterID("Sabah");
                }
                else if (KedahRadio.isSelected()){
                    sportCenterID = getSportCenterID("Kedah");
                }
                else if (SarawakRadio.isSelected()){
                    sportCenterID = getSportCenterID("Sarawak");
                }
                else{
                    sportCenterID = "MISSING";
                }
                br.close();
                BufferedWriter bw = new BufferedWriter(new FileWriter("Sport Records.txt", true));
                bw.write(sportID + "\t" + sportName + "\t" + sportCenterID + "\n");
                bw.close();
                try {
                    BufferedReader cbr = new BufferedReader(new FileReader("Coach Records.txt"));
                    String temp;
                    String[] data;
                    String[] fileContent = cbr.lines().collect(Collectors.joining("\n")).split("\n", -1);
                    for (int i = 0; i < fileContent.length; i++){
                        data = fileContent[i].split("\t", -1);
                        if (sportName.equals(data[10]) && sportCenterID.equals(data[7])) {
                            data[9] = sportID;
                            Array.set(fileContent, i, data[0] + "\t" + data[1] + "\t" + data[2] + "\t" + data[3] + "\t" + data[4] + "\t" + data[5] + "\t" + data[6] + "\t" + data[7] + "\t" + data[8] + "\t" + data[9] + "\t" + data[10] + "\t" + data[11]);                            
                        }
                    }
                    cbr.close();
                    BufferedWriter cbw = new BufferedWriter(new FileWriter("Coach Records.txt"));
                    for (int i = 0; i < fileContent.length; i++){
                        cbw.write(fileContent[i] + "\n");
                    }
                    cbw.close();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                }
                JOptionPane.showMessageDialog(this, "Sport record added successfully", "Confirmation Message", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void SportNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportNameComboBoxActionPerformed
        updateRadioButton();
    }//GEN-LAST:event_SportNameComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddSport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AdminAddSportLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton KedahRadio;
    private javax.swing.JRadioButton KualaLumpurRadio;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JRadioButton SabahRadio;
    private javax.swing.JRadioButton SarawakRadio;
    private javax.swing.JRadioButton SelangorRadio;
    private javax.swing.JLabel SportCenterLabel;
    private javax.swing.JComboBox<String> SportNameComboBox;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
