/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author System Manager
 */
public class AdminAddRecord extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddRecord
     */
    public AdminAddRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminModifyRecordLabel = new javax.swing.JLabel();
        AddCoachButton = new javax.swing.JButton();
        AddSportButton = new javax.swing.JButton();
        AddSportScheduleButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 450));

        AdminModifyRecordLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        AdminModifyRecordLabel.setText("Add record of...");

        AddCoachButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AddCoachButton.setText("Coach");
        AddCoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCoachButtonActionPerformed(evt);
            }
        });

        AddSportButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AddSportButton.setText("Sport");
        AddSportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSportButtonActionPerformed(evt);
            }
        });

        AddSportScheduleButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        AddSportScheduleButton.setLabel("Sport Schedule");
        AddSportScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSportScheduleButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(69, Short.MAX_VALUE)
                        .addComponent(AdminModifyRecordLabel)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddSportButton)
                    .addComponent(AddCoachButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddSportScheduleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(AdminModifyRecordLabel)
                .addGap(25, 25, 25)
                .addComponent(AddCoachButton)
                .addGap(36, 36, 36)
                .addComponent(AddSportButton)
                .addGap(40, 40, 40)
                .addComponent(AddSportScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddCoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCoachButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminAddCoach aac = new AdminAddCoach();
        aac.setVisible(true);
    }//GEN-LAST:event_AddCoachButtonActionPerformed

    private void AddSportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSportButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminAddSport aas = new AdminAddSport();
        aas.setVisible(true);
    }//GEN-LAST:event_AddSportButtonActionPerformed

    private void AddSportScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSportScheduleButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminAddSportSchedule aass = new AdminAddSportSchedule();
        aass.setVisible(true);
    }//GEN-LAST:event_AddSportScheduleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCoachButton;
    private javax.swing.JButton AddSportButton;
    private javax.swing.JButton AddSportScheduleButton;
    private javax.swing.JLabel AdminModifyRecordLabel;
    private javax.swing.JButton BackButton;
    // End of variables declaration//GEN-END:variables
}
