/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author System Manager
 */
public class AdminAddCoach extends javax.swing.JFrame {

    Date date;
    /**
     * Creates new form AdminAddCoach
     */
    public AdminAddCoach() {
        initComponents();
        this.date = new Date(DayBox.getSelectedItem().toString(), MonthBox.getSelectedItem().toString(), YearBox.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddCoachLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        DateLabel1 = new javax.swing.JLabel();
        HourlyRateLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        PostalCodeLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        StateBox = new javax.swing.JComboBox<>();
        SportCenterLabel = new javax.swing.JLabel();
        SportLabel = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        DayBox = new javax.swing.JComboBox<>();
        MonthBox = new javax.swing.JComboBox<>();
        YearBox = new javax.swing.JComboBox<>();
        DateLabel2 = new javax.swing.JLabel();
        DateLabel3 = new javax.swing.JLabel();
        HourlyRateText = new javax.swing.JTextField();
        RMLabel = new javax.swing.JLabel();
        PhoneText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        PostalCodeText = new javax.swing.JTextField();
        SportCenterBox = new javax.swing.JComboBox<>();
        SportBox = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CityLabel = new javax.swing.JLabel();
        CityText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddCoachLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        AddCoachLabel.setText("Add Coach Record");

        NameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        NameLabel.setText("Name:");

        DateLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        DateLabel1.setText("Date Joined:");

        HourlyRateLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        HourlyRateLabel.setText("Hourly Rate:");

        PhoneLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone:");

        AddressLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AddressLabel.setText("Address:");

        PostalCodeLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        PostalCodeLabel.setText("Postal Code:");

        StateLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        StateLabel.setText("State:");

        StateBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        StateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Kedah", "Kelantan", "Malacca", "Negeri Sembilan", "Pahang", "Penang", "Perak", "Perlis", "Sabah", "Sarawak", "Selangor", "Terengganu", "Kuala Lumpur", "Labuan", "Putrajaya" }));
        StateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateBoxActionPerformed(evt);
            }
        });

        SportCenterLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportCenterLabel.setText("Sport Center:");

        SportLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportLabel.setText("Sport:");

        NameText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        DayBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        DayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DayBox.setToolTipText("");
        DayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayBoxActionPerformed(evt);
            }
        });

        MonthBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        MonthBox.setToolTipText("");
        MonthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthBoxActionPerformed(evt);
            }
        });

        YearBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        YearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        YearBox.setToolTipText("");
        YearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearBoxActionPerformed(evt);
            }
        });

        DateLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        DateLabel2.setText("/");

        DateLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        DateLabel3.setText("/");

        HourlyRateText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        RMLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        RMLabel.setText("RM");

        PhoneText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        AddressText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        PostalCodeText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        SportCenterBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SportCenterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SC001 (Kuala Lumpur)", "SC002 (Selangor)", "SC003 (Sabah)", "SC004 (Kedah)", "SC005 (Sarawak)" }));

        SportBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SportBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Football", "Archery", "Gymnastics", "Volleyball", "Basketball", "Cricket", "Tennis", "Table Tennis" }));

        AddButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CityLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CityLabel.setText("City:");

        CityText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PostalCodeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PostalCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DateLabel1)
                                            .addComponent(NameLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(RMLabel)
                                                                .addComponent(DateLabel2))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGap(22, 22, 22)
                                                                    .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(HourlyRateText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(DateLabel3))
                                                        .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(DayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(182, 182, 182)
                                                    .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(BackButton)
                                    .addComponent(HourlyRateLabel)
                                    .addComponent(PhoneLabel)
                                    .addComponent(AddressLabel)
                                    .addComponent(AddButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SportCenterLabel)
                                            .addComponent(SportLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SportBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SportCenterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CityLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddCoachLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(AddCoachLabel)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel1)
                    .addComponent(DayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLabel2)
                    .addComponent(DateLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourlyRateLabel)
                    .addComponent(HourlyRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RMLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PostalCodeLabel)
                        .addComponent(PostalCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StateLabel)
                        .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportCenterLabel)
                    .addComponent(SportCenterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportLabel)
                    .addComponent(SportBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddButton)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAndAddItem(DefaultComboBoxModel model, Object object){
        if (model.getIndexOf(object) == -1){
            model.addElement(object);
        }
    }
    
    private void DayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayBoxActionPerformed
           date.day = (String)DayBox.getSelectedItem();
    }//GEN-LAST:event_DayBoxActionPerformed

    private void MonthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthBoxActionPerformed
        DefaultComboBoxModel model = (DefaultComboBoxModel)DayBox.getModel();
        date.month = (String)MonthBox.getSelectedItem();
        switch (date.getMonthType()){
            case 0:{
                checkAndAddItem(model, "29");
                checkAndAddItem(model, "30");
                checkAndAddItem(model, "31");
                break;
            }
            case 1:{
                checkAndAddItem(model, "29");
                checkAndAddItem(model, "29");
                DayBox.removeItem("31");
                break;
            }
            case 2:{
                DayBox.removeItem("30");
                DayBox.removeItem("31");
                if (!date.isLeapYear()){
                    DayBox.removeItem("29");
                }
            }
        }
    }//GEN-LAST:event_MonthBoxActionPerformed

    private void YearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearBoxActionPerformed
        DefaultComboBoxModel model = (DefaultComboBoxModel)DayBox.getModel();
        date.year = (String)YearBox.getSelectedItem();
        if (date.isLeapYear()){
            if (date.month.equals("2")){
                checkAndAddItem(model, "29");
            }
        }
        else{
            DayBox.removeItem("29");
        }
    }//GEN-LAST:event_YearBoxActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminAddRecord aar = new AdminAddRecord();
        aar.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void StateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateBoxActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if (NameText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a name.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(HourlyRateText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter an hourly rate.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            float HourlyRate = Float.parseFloat(HourlyRateText.getText().trim());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter a valid hourly rate.", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        if(PhoneText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a phone number.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(AddressText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter an address.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(PostalCodeText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a postal code.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(CityText.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a city name.", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Coach c = new Coach(NameText.getText(), String.format("%s/%s/%s", date.day, date.month, date.year), "None", Float.parseFloat(HourlyRateText.getText()), PhoneText.getText(), String.format("%s, %s, %s, %s", AddressText.getText(), PostalCodeText.getText(), CityText.getText(), StateBox.getSelectedItem().toString()), SportCenterBox.getSelectedItem().toString().split(" ")[0], "None", SportBox.getSelectedItem().toString(), "None");
        int e = c.addRecord();
        if (e == 0){
            JOptionPane.showMessageDialog(this, "Coach record added successfully.", "Confirmation Message", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddCoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddCoachLabel;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressText;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CityText;
    private javax.swing.JLabel DateLabel1;
    private javax.swing.JLabel DateLabel2;
    private javax.swing.JLabel DateLabel3;
    private javax.swing.JComboBox<String> DayBox;
    private javax.swing.JLabel HourlyRateLabel;
    private javax.swing.JTextField HourlyRateText;
    private javax.swing.JComboBox<String> MonthBox;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JLabel PostalCodeLabel;
    private javax.swing.JTextField PostalCodeText;
    private javax.swing.JLabel RMLabel;
    private javax.swing.JComboBox<String> SportBox;
    private javax.swing.JComboBox<String> SportCenterBox;
    private javax.swing.JLabel SportCenterLabel;
    private javax.swing.JLabel SportLabel;
    private javax.swing.JComboBox<String> StateBox;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JComboBox<String> YearBox;
    // End of variables declaration//GEN-END:variables
}
