/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author jerem
 */
public class AdminSearchSpecificRecords extends javax.swing.JFrame {

    /**
     * Creates new form SearchSpecificRecordsPage
     */
    public AdminSearchSpecificRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchSpecificRecordsLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        SearchCoachRecordsButton = new javax.swing.JButton();
        SearchSportRecordsButton = new javax.swing.JButton();
        SearchStudentRecordsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchSpecificRecordsLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        SearchSpecificRecordsLabel.setForeground(new java.awt.Color(0, 0, 0));
        SearchSpecificRecordsLabel.setText("Search Specific Records Page");

        BackButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        SearchCoachRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        SearchCoachRecordsButton.setText("Search Coach Records");
        SearchCoachRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCoachRecordsButtonActionPerformed(evt);
            }
        });

        SearchSportRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        SearchSportRecordsButton.setText("Search Sport Record");
        SearchSportRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSportRecordsButtonActionPerformed(evt);
            }
        });

        SearchStudentRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        SearchStudentRecordsButton.setText("Search Student Record");
        SearchStudentRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentRecordsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SearchSpecificRecordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(SearchCoachRecordsButton)
                        .addGap(60, 60, 60)
                        .addComponent(SearchSportRecordsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(SearchStudentRecordsButton)
                        .addContainerGap(47, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(SearchSpecificRecordsLabel)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCoachRecordsButton)
                    .addComponent(SearchSportRecordsButton)
                    .addComponent(SearchStudentRecordsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SearchSportRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSportRecordsButtonActionPerformed
        this.setVisible(false);
        AdminSearchSportRecord sp = new AdminSearchSportRecord();
        sp.setVisible(true);
    }//GEN-LAST:event_SearchSportRecordsButtonActionPerformed

    private void SearchCoachRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCoachRecordsButtonActionPerformed
        this.setVisible(false);
        AdminSearchCoachRecords sp = new AdminSearchCoachRecords();
        sp.setVisible(true);
    }//GEN-LAST:event_SearchCoachRecordsButtonActionPerformed

    private void SearchStudentRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentRecordsButtonActionPerformed
        this.setVisible(false);
        AdminSearchStudentRecord sp = new AdminSearchStudentRecord();
        sp.setVisible(true);
    }//GEN-LAST:event_SearchStudentRecordsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSearchSpecificRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSearchSpecificRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSearchSpecificRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSearchSpecificRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSearchSpecificRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton SearchCoachRecordsButton;
    private javax.swing.JLabel SearchSpecificRecordsLabel;
    private javax.swing.JButton SearchSportRecordsButton;
    private javax.swing.JButton SearchStudentRecordsButton;
    // End of variables declaration//GEN-END:variables
}
