/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author System Manager
 */
public class AdminModifySport extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddSport
     */
    public AdminModifySport() {
        initComponents();
        try{
            BufferedReader br = new BufferedReader(new FileReader("Sport Records.txt"));
            Object[] lines;
            String[] data;
            lines = br.lines().toArray();
            for (int i = 0; i < lines.length; i++){
                data = lines[i].toString().split("\t");
                SportIDComboBox.addItem(data[0]);
            }
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        updateDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        AdminModifySportLabel = new javax.swing.JLabel();
        SportNameLabel = new javax.swing.JLabel();
        SportCenterLabel = new javax.swing.JLabel();
        SportIDComboBox = new javax.swing.JComboBox<>();
        SportIDLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        KualaLumpurRadio = new javax.swing.JRadioButton();
        SelangorRadio = new javax.swing.JRadioButton();
        SabahRadio = new javax.swing.JRadioButton();
        SarawakRadio = new javax.swing.JRadioButton();
        KedahRadio = new javax.swing.JRadioButton();
        SportNameComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 600));

        AdminModifySportLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        AdminModifySportLabel.setText("Modify Sport Record");

        SportNameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportNameLabel.setText("Sport Name:");

        SportCenterLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportCenterLabel.setText("Available Sport Center:");

        SportIDComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SportIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportIDComboBoxActionPerformed(evt);
            }
        });

        SportIDLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportIDLabel.setText("Sport ID:");

        UpdateButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setEnabled(false);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(KualaLumpurRadio);
        KualaLumpurRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KualaLumpurRadio.setText("Kuala Lumpur");
        KualaLumpurRadio.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("SC001"), KualaLumpurRadio, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup1.add(SelangorRadio);
        SelangorRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SelangorRadio.setText("Selangor");
        SelangorRadio.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("SC002"), SelangorRadio, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup1.add(SabahRadio);
        SabahRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SabahRadio.setText("Sabah");
        SabahRadio.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("SC003"), SabahRadio, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup1.add(SarawakRadio);
        SarawakRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SarawakRadio.setText("Sarawak");
        SarawakRadio.setActionCommand("SC005");
        SarawakRadio.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("SC005"), SarawakRadio, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        buttonGroup1.add(KedahRadio);
        KedahRadio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KedahRadio.setText("Kedah");
        KedahRadio.setActionCommand("SC004");
        KedahRadio.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, buttonGroup1, org.jdesktop.beansbinding.ELProperty.create("SC004"), KedahRadio, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        SportNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Football", "Archery", "Gymnastics", "Volleyball", "Basketball", "Cricket", "Tennis", "Table Tennis" }));
        SportNameComboBox.setEnabled(false);
        SportNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportNameComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KedahRadio)
                                .addGap(18, 18, 18)
                                .addComponent(SarawakRadio))
                            .addComponent(SportCenterLabel)
                            .addComponent(UpdateButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SportIDLabel)
                                    .addComponent(SportNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(SportNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SportIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KualaLumpurRadio)
                                .addGap(18, 18, 18)
                                .addComponent(SelangorRadio)
                                .addGap(18, 18, 18)
                                .addComponent(SabahRadio))
                            .addComponent(AdminModifySportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(AdminModifySportLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SportIDLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportNameLabel)
                    .addComponent(SportNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SportCenterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KualaLumpurRadio)
                    .addComponent(SelangorRadio)
                    .addComponent(SabahRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SarawakRadio)
                    .addComponent(KedahRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(UpdateButton)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateDetails(){
         try{
            BufferedReader br = new BufferedReader(new FileReader("Sport Records.txt"));
            Object[] lines = br.lines().toArray();
            String[] data;
            for (int i = 0; i < lines.length; i++){
                data = lines[i].toString().split("\t");
                if (data[0].equals(SportIDComboBox.getSelectedItem().toString())){
                    SportNameComboBox.setSelectedItem(data[1]);
                    if (data[2].equals("SC001")){
                        KualaLumpurRadio.setSelected(true);
                    }
                    else if (data[2].equals("SC002")){
                        SelangorRadio.setSelected(true);
                    }
                    else if (data[2].equals("SC003")){
                        SabahRadio.setSelected(true);
                    }
                    else if (data[2].equals("SC004")){
                        KedahRadio.setSelected(true);
                    }
                    else if (data[2].equals("SC005")){
                        SarawakRadio.setSelected(true);
                    }
             
                }
            }
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        if (SportIDComboBox.getSelectedItem() != null){
            SportNameComboBox.setEnabled(true);
            KualaLumpurRadio.setEnabled(true);
            SelangorRadio.setEnabled(true);
            SabahRadio.setEnabled(true);
            SarawakRadio.setEnabled(true);
            KedahRadio.setEnabled(true);
            UpdateButton.setEnabled(true);
        }       
    }
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminModifyRecord amr = new AdminModifyRecord();
        amr.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SportIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportIDComboBoxActionPerformed
        updateDetails();
    }//GEN-LAST:event_SportIDComboBoxActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try{ 
            BufferedReader br = new BufferedReader(new FileReader("Sport Records.txt"));
            Object[] lines = br.lines().toArray();
            String[] data = null;
            for (int i = 0; i < lines.length; i++){
                data = lines[i].toString().split("\t");
                if (!data[0].equals(SportIDComboBox.getSelectedItem()) && data[1].equals(SportNameComboBox.getSelectedItem()) && data[2].equals(buttonGroup1.getSelection().getActionCommand())){
                    JOptionPane.showMessageDialog(this, "Unable to modify record. Record duplicate exists.", "Error Message", JOptionPane.ERROR_MESSAGE);
                    br.close();
                    return;
                }
            }
            for (int i = 0; i < lines.length; i++){
                data = lines[i].toString().split("\t");
                if (data[0].equals(SportIDComboBox.getSelectedItem())){
                    lines[i] = SportIDComboBox.getSelectedItem() + "\t" + SportNameComboBox.getSelectedItem() + "\t" + buttonGroup1.getSelection().getActionCommand();
                    break;
                }
            }
            br.close();
            BufferedWriter bw = new BufferedWriter(new FileWriter("Sport Records.txt"));
            for (int i = 0; i < lines.length; i++){
                bw.write(lines[i].toString());
                bw.newLine();
            }
            bw.close();
            BufferedReader cbr = new BufferedReader(new FileReader("Coach Records.txt"));
            lines = cbr.lines().toArray();
            for (int i = 0; i < lines.length; i++){
                data = lines[i].toString().split("\t");
                if (data[9].equals(SportIDComboBox.getSelectedItem())){
                    if (!data[10].equals(SportNameComboBox.getSelectedItem()) || !data[7].equals(buttonGroup1.getSelection().getActionCommand())){
                        lines[i] = data[0] + "\t" + data[1] + "\t" + data[2] + "\t" + data[3] + "\t" + data[4] + "\t" + data[5] + "\t" + data[6] + "\t" + data[7] + "\t" + data[8] + "\t" + "None" + "\t" + data[10] + "\t" + data[11];
                    }
                }
                else if (data[7].equals(buttonGroup1.getSelection().getActionCommand()) && data[10].equals(SportNameComboBox.getSelectedItem())){
                    lines[i] = data[0] + "\t" + data[1] + "\t" + data[2] + "\t" + data[3] + "\t" + data[4] + "\t" + data[5] + "\t" + data[6] + "\t" + data[7] + "\t" + data[8] + "\t" + SportIDComboBox.getSelectedItem() + "\t" + data[10] + "\t" + data[11];
                }
            }
            cbr.close();
            BufferedWriter cbw = new BufferedWriter(new FileWriter("Coach Records.txt"));
            for (int i = 0; i < lines.length; i++){
                cbw.write(lines[i].toString());
                cbw.newLine();
            }
            cbw.close();
            JOptionPane.showMessageDialog(this, "Sport record updated successfully.", "Confirmation Message", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SportNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportNameComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModifySport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModifySport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminModifySportLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton KedahRadio;
    private javax.swing.JRadioButton KualaLumpurRadio;
    private javax.swing.JRadioButton SabahRadio;
    private javax.swing.JRadioButton SarawakRadio;
    private javax.swing.JRadioButton SelangorRadio;
    private javax.swing.JLabel SportCenterLabel;
    private javax.swing.JComboBox<String> SportIDComboBox;
    private javax.swing.JLabel SportIDLabel;
    private javax.swing.JComboBox<String> SportNameComboBox;
    private javax.swing.JLabel SportNameLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
