/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author jerem
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPageLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        AddRecordsButton = new javax.swing.JButton();
        DisplayAllRecordsButton = new javax.swing.JButton();
        SearchSpecificRecordsButton = new javax.swing.JButton();
        SortAndDisplayCoachRecordsButton = new javax.swing.JButton();
        ModifyRecordsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 540));

        AdminPageLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        AdminPageLabel.setForeground(new java.awt.Color(0, 0, 0));
        AdminPageLabel.setText("Admin Page");

        WelcomeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        WelcomeLabel.setText("Welcome back, admin.");

        AddRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        AddRecordsButton.setText("Add Records");
        AddRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecordsButtonActionPerformed(evt);
            }
        });

        DisplayAllRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        DisplayAllRecordsButton.setText("Display All Records");
        DisplayAllRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllRecordsButtonActionPerformed(evt);
            }
        });

        SearchSpecificRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        SearchSpecificRecordsButton.setText("Search Specifc Records");
        SearchSpecificRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSpecificRecordsButtonActionPerformed(evt);
            }
        });

        SortAndDisplayCoachRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        SortAndDisplayCoachRecordsButton.setText("Sort and Display Coach Records");
        SortAndDisplayCoachRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortAndDisplayCoachRecordsButtonActionPerformed(evt);
            }
        });

        ModifyRecordsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ModifyRecordsButton.setText("Modify Records");
        ModifyRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRecordsButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AdminPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(WelcomeLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(SortAndDisplayCoachRecordsButton)
                                .addGap(163, 163, 163)
                                .addComponent(ModifyRecordsButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(AddRecordsButton)
                                .addGap(112, 112, 112)
                                .addComponent(DisplayAllRecordsButton)
                                .addGap(70, 70, 70)
                                .addComponent(SearchSpecificRecordsButton)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(WelcomeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addComponent(AdminPageLabel)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddRecordsButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SearchSpecificRecordsButton)
                                .addComponent(DisplayAllRecordsButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SortAndDisplayCoachRecordsButton)
                            .addComponent(ModifyRecordsButton))
                        .addGap(149, 149, 149)))
                .addComponent(LogoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.setVisible(false);
        HomePage hp = new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void SearchSpecificRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSpecificRecordsButtonActionPerformed
        this.setVisible(false);
        AdminSearchSpecificRecords sp = new AdminSearchSpecificRecords();
        sp.setVisible(true);
    }//GEN-LAST:event_SearchSpecificRecordsButtonActionPerformed

    private void SortAndDisplayCoachRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortAndDisplayCoachRecordsButtonActionPerformed
        this.setVisible(false);
        AdminSortAndDisplayCoachRecords sp = new AdminSortAndDisplayCoachRecords();
        sp.displayCoachRecords();
        sp.setVisible(true);
    }//GEN-LAST:event_SortAndDisplayCoachRecordsButtonActionPerformed

    private void AddRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecordsButtonActionPerformed
        this.setVisible(false);
        AdminAddRecord ar = new AdminAddRecord();
        ar.setVisible(true);
    }//GEN-LAST:event_AddRecordsButtonActionPerformed

    private void DisplayAllRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllRecordsButtonActionPerformed
        this.setVisible(false);
        AdminDisplayRecord ar = new AdminDisplayRecord();
        ar.setVisible(true);
    }//GEN-LAST:event_DisplayAllRecordsButtonActionPerformed

    private void ModifyRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRecordsButtonActionPerformed
        this.setVisible(false);
        AdminModifyRecord ar = new AdminModifyRecord();
        ar.setVisible(true);
    }//GEN-LAST:event_ModifyRecordsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRecordsButton;
    private javax.swing.JLabel AdminPageLabel;
    private javax.swing.JButton DisplayAllRecordsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ModifyRecordsButton;
    private javax.swing.JButton SearchSpecificRecordsButton;
    private javax.swing.JButton SortAndDisplayCoachRecordsButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
