/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author System Manager
 */
public class AdminDisplayRecord extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddRecord
     */
    public AdminDisplayRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminDisplayRecordLabel = new javax.swing.JLabel();
        DisplayCoachButton = new javax.swing.JButton();
        DisplaySportButton = new javax.swing.JButton();
        DisplayRegisteredStudentButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 450));

        AdminDisplayRecordLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        AdminDisplayRecordLabel.setText("Display record of...");

        DisplayCoachButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DisplayCoachButton.setText("Coach");
        DisplayCoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCoachButtonActionPerformed(evt);
            }
        });

        DisplaySportButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DisplaySportButton.setText("Sport");
        DisplaySportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaySportButtonActionPerformed(evt);
            }
        });

        DisplayRegisteredStudentButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DisplayRegisteredStudentButton.setText("Registered Student");
        DisplayRegisteredStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRegisteredStudentButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addComponent(AdminDisplayRecordLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayRegisteredStudentButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DisplaySportButton)
                        .addComponent(DisplayCoachButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(AdminDisplayRecordLabel)
                .addGap(25, 25, 25)
                .addComponent(DisplayCoachButton)
                .addGap(30, 30, 30)
                .addComponent(DisplaySportButton)
                .addGap(29, 29, 29)
                .addComponent(DisplayRegisteredStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DisplayCoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCoachButtonActionPerformed
        this.setVisible(false);
        AdminDisplayCoach adc = new AdminDisplayCoach();
        adc.setVisible(true);
    }//GEN-LAST:event_DisplayCoachButtonActionPerformed

    private void DisplaySportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaySportButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminDisplaySport ads = new AdminDisplaySport();
        ads.setVisible(true);
    }//GEN-LAST:event_DisplaySportButtonActionPerformed

    private void DisplayRegisteredStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRegisteredStudentButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminDisplayRegisteredStudent adrs = new AdminDisplayRegisteredStudent();
        adrs.setVisible(true);
    }//GEN-LAST:event_DisplayRegisteredStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDisplayRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDisplayRecordLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DisplayCoachButton;
    private javax.swing.JButton DisplayRegisteredStudentButton;
    private javax.swing.JButton DisplaySportButton;
    // End of variables declaration//GEN-END:variables
}
