/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author System Manager
 */
public class StudentViewSelfrecord extends javax.swing.JFrame {

    /**
     * Creates new form StudentViewSelfrecord
     */
    public StudentViewSelfrecord() {
        initComponents();
        try{
            BufferedReader br = new BufferedReader(new FileReader("Student Records.txt"));
            Object[] lines;
            lines = br.lines().toArray();
            String[] data;
            String sportCenterName = "MISSING";
            List<String> sportName = new ArrayList<String>();
            for (int i = 0; i < lines.length; i++) {
                if ((data = lines[i].toString().split("\t"))[0].equals(LoginSession.StudentID)) {
                    /* how to access username? */
                    try{
                        BufferedReader scbr = new BufferedReader(new FileReader("Sport Centers.txt"));
                        String temp;
                        String[] sportCenterData;
                        while ((temp = scbr.readLine()) != null){
                            if ((sportCenterData = temp.split("\t"))[0].equals(data[7])){
                                sportCenterName = sportCenterData[1];
                                break;
                            }
                        }
                        scbr.close();
                        BufferedReader sbr = new BufferedReader(new FileReader("Sport Records.txt"));
                        String[] sportData;
                        String[] sportID;
                        while ((temp = sbr.readLine()) != null){
                            sportData = temp.split("\t");    
                            sportID = data[5].split(", ");
                            for (int j = 0; j < sportID.length; j++){    /* delimiter */
                                if (sportID[j].equals(sportData[0])){
                                    if (!sportName.contains(sportData[1])){
                                        sportName.add(sportData[1]);
                                    }
                                    break;
                                }
                            }
                        }
                        sbr.close();
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                    }
                    NameText.setText(data[1]);
                    UsernameText.setText(data[2]);
                    GenderText.setText(data[4]);                    
                    SportCenterText.setText(sportCenterName);
                    SportText.setText(String.join("," , sportName));
                }
            }
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        SportCenterLabel = new javax.swing.JLabel();
        SportLabel = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        GenderText = new javax.swing.JTextField();
        UsernameText = new javax.swing.JTextField();
        SportCenterText = new javax.swing.JTextField();
        SportText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 450));

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("View Self-record");

        NameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        NameLabel.setText("Name:");

        GenderLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderLabel.setText("Gender:");

        UsernameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameLabel.setText("Username:");

        SportCenterLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportCenterLabel.setText("Sport Center:");

        SportLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportLabel.setText("Sport:");

        NameText.setEditable(false);
        NameText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        GenderText.setEditable(false);
        GenderText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        UsernameText.setEditable(false);
        UsernameText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        SportCenterText.setEditable(false);
        SportCenterText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        SportText.setEditable(false);
        SportText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel)
                            .addComponent(GenderLabel)
                            .addComponent(UsernameLabel)
                            .addComponent(SportCenterLabel)
                            .addComponent(SportLabel)
                            .addComponent(BackButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SportText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SportCenterText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportCenterLabel)
                    .addComponent(SportCenterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportLabel)
                    .addComponent(SportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentViewDetails svd = new StudentViewDetails();
        svd.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewSelfrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewSelfrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewSelfrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewSelfrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewSelfrecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField GenderText;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel SportCenterLabel;
    private javax.swing.JTextField SportCenterText;
    private javax.swing.JLabel SportLabel;
    private javax.swing.JTextField SportText;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
