/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author System Manager
 */
public class StudentViewCoach extends javax.swing.JFrame {

    /**
     * Creates new form StudentViewCoach
     */
    public StudentViewCoach() {
        initComponents();
        try{
            BufferedReader br = new BufferedReader(new FileReader("Coach Records.txt"));
            Object[] lines = br.lines().toArray();
            for (int i = 0; i < lines.length; i++){
                CoachComboBox.addItem(lines[i].toString().split("\t")[0]);
            }
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        updateDetails();
    }
    
    public void updateDetails(){
        try{
            BufferedReader br = new BufferedReader(new FileReader("Coach Records.txt"));
            String sportCenterName = "MISSING";
            Object[] lines = br.lines().toArray();
            String[] data;
            for (int i = 0; i < lines.length; i++){
                data = lines[i].toString().split("\t");
                if (data[0].equals(CoachComboBox.getSelectedItem().toString())){
                    try{
                        BufferedReader scbr = new BufferedReader(new FileReader("Sport Centers.txt"));
                        String temp;
                        String[] scdata;
                        while((temp = scbr.readLine()) != null){
                            scdata = temp.split("\t");
                            if (data[7].equals(scdata[0])){
                                sportCenterName = scdata[1];
                                break;
                            }
                        }
                        scbr.close();
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                    }
                    CoachIDText.setText(data[0]);
                    NameText.setText(data[1]);
                    DateJoinedText.setText(data[2]);
                    DateTerminatedText.setText(data[3]);
                    PhoneText.setText(data[5]);
                    SportCenterText.setText(sportCenterName);
                    SportText.setText(data[9] + " (" + data[10] + ")");
                    RatingText.setText(data[11]);
                }
            }
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error opening file!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoachComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CoachIDLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        DateJoinedLabel = new javax.swing.JLabel();
        DateTerminatedLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        SportCenterLabel = new javax.swing.JLabel();
        SportLabel = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        CoachIDText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        DateJoinedText = new javax.swing.JTextField();
        DateTerminatedText = new javax.swing.JTextField();
        PhoneText = new javax.swing.JTextField();
        SportCenterText = new javax.swing.JTextField();
        SportText = new javax.swing.JTextField();
        RatingText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 540));

        CoachComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CoachComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Coach Details");

        CoachIDLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CoachIDLabel.setText("Coach ID:");

        NameLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        NameLabel.setText("Name:");

        DateJoinedLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        DateJoinedLabel.setText("Date Joined:");

        DateTerminatedLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        DateTerminatedLabel.setText("Date Terminated:");

        PhoneLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone:");

        SportCenterLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportCenterLabel.setText("Sport Center:");

        SportLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SportLabel.setText("Sport:");

        RatingLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        RatingLabel.setText("Rating:");

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CoachIDText.setEditable(false);
        CoachIDText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        NameText.setEditable(false);
        NameText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        DateJoinedText.setEditable(false);
        DateJoinedText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        DateTerminatedText.setEditable(false);
        DateTerminatedText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        PhoneText.setEditable(false);
        PhoneText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        SportCenterText.setEditable(false);
        SportCenterText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SportCenterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportCenterTextActionPerformed(evt);
            }
        });

        SportText.setEditable(false);
        SportText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        RatingText.setEditable(false);
        RatingText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 289, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CoachIDLabel)
                    .addComponent(NameLabel)
                    .addComponent(DateJoinedLabel)
                    .addComponent(DateTerminatedLabel)
                    .addComponent(PhoneLabel)
                    .addComponent(SportCenterLabel)
                    .addComponent(SportLabel)
                    .addComponent(RatingLabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RatingText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SportText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SportCenterText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTerminatedText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateJoinedText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoachIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(CoachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(CoachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoachIDLabel)
                    .addComponent(CoachIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateJoinedLabel)
                    .addComponent(DateJoinedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateTerminatedLabel)
                    .addComponent(DateTerminatedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportCenterLabel)
                    .addComponent(SportCenterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportLabel)
                    .addComponent(SportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingLabel)
                    .addComponent(RatingText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentViewDetails svd = new StudentViewDetails();
        svd.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SportCenterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportCenterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportCenterTextActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void CoachComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachComboBoxActionPerformed
        updateDetails();
    }//GEN-LAST:event_CoachComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewCoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> CoachComboBox;
    private javax.swing.JLabel CoachIDLabel;
    private javax.swing.JTextField CoachIDText;
    private javax.swing.JLabel DateJoinedLabel;
    private javax.swing.JTextField DateJoinedText;
    private javax.swing.JLabel DateTerminatedLabel;
    private javax.swing.JTextField DateTerminatedText;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneText;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JTextField RatingText;
    private javax.swing.JLabel SportCenterLabel;
    private javax.swing.JTextField SportCenterText;
    private javax.swing.JLabel SportLabel;
    private javax.swing.JTextField SportText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
