/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author jerem
 */
public class StudentFeedback extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackPage
     */
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    
    public StudentFeedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FeedbackPageLabel = new javax.swing.JLabel();
        CoachLabel = new javax.swing.JLabel();
        CoachComboBox = new javax.swing.JComboBox<>();
        RatingSlider = new javax.swing.JSlider();
        RatingLabel = new javax.swing.JLabel();
        FeedbackLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FeedbackTextArea = new javax.swing.JTextArea();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FeedbackPageLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        FeedbackPageLabel.setForeground(new java.awt.Color(0, 0, 0));
        FeedbackPageLabel.setText("Feedback Page");

        CoachLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        CoachLabel.setForeground(new java.awt.Color(0, 0, 0));
        CoachLabel.setText("Coach:");

        CoachComboBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        CoachComboBox.setModel(model);

        RatingSlider.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RatingSlider.setForeground(new java.awt.Color(0, 0, 0));
        RatingSlider.setMajorTickSpacing(1);
        RatingSlider.setMaximum(5);
        RatingSlider.setMinimum(1);
        RatingSlider.setPaintLabels(true);
        RatingSlider.setPaintTicks(true);
        RatingSlider.setSnapToTicks(true);
        RatingSlider.setToolTipText("");
        RatingSlider.setValue(3);

        RatingLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        RatingLabel.setForeground(new java.awt.Color(0, 0, 0));
        RatingLabel.setText("Rating:");

        FeedbackLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        FeedbackLabel.setForeground(new java.awt.Color(0, 0, 0));
        FeedbackLabel.setText("Feedback:");

        FeedbackTextArea.setColumns(20);
        FeedbackTextArea.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        FeedbackTextArea.setRows(5);
        FeedbackTextArea.setText("(optional)");
        jScrollPane1.setViewportView(FeedbackTextArea);

        SubmitButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(157, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CoachLabel)
                                    .addComponent(RatingLabel)
                                    .addComponent(FeedbackLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RatingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CoachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton)))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FeedbackPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(FeedbackPageLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoachLabel)
                    .addComponent(CoachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RatingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RatingLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeedbackLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void displayCoachNames() {
        List<String> coachNames = Student.getCoachNames();
        for (String coachName: coachNames) {
            model.addElement(coachName);
        }
    }
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        StudentPage sp = new StudentPage();
        sp.displayUsername(LoginSession.Username);
        sp.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String CoachID, feedback;
        int rating;
        CoachID = String.valueOf(CoachComboBox.getSelectedItem());
        CoachID = CoachID.substring(CoachID.indexOf('(') + 1, CoachID.indexOf(')'));
        rating = RatingSlider.getValue();
        feedback = FeedbackTextArea.getText();
        if (feedback.equals("(optional)")) {
            feedback = "None";
        }
        int result = Student.writeFeedback(CoachID, Integer.toString(rating), feedback);
        switch (result) {
            case 0:
                JOptionPane.showMessageDialog(this, "Feedback submission process completed!", "Congratualations", JOptionPane.ERROR_MESSAGE);
                break;
            case -1:
                JOptionPane.showMessageDialog(this, "Error writing into file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> CoachComboBox;
    private javax.swing.JLabel CoachLabel;
    private javax.swing.JLabel FeedbackLabel;
    private javax.swing.JLabel FeedbackPageLabel;
    private javax.swing.JTextArea FeedbackTextArea;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JSlider RatingSlider;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
