/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

import javax.swing.JOptionPane;

/**
 *
 * @author jerem
 */
public class StudentModifyProfile extends javax.swing.JFrame {

    /**
     * Creates new form ModifyProfilePage
     */
    public StudentModifyProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifyProfileLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        GenderCombo = new javax.swing.JComboBox<>();
        AgeSpinner = new javax.swing.JSpinner();
        ModifyButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        PasswordText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModifyProfileLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        ModifyProfileLabel.setForeground(new java.awt.Color(0, 0, 0));
        ModifyProfileLabel.setText("Modify Profile Page");

        AgeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(0, 0, 0));
        AgeLabel.setText("Age:");

        NameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 0, 0));
        NameLabel.setText("Name:");

        PasswordLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Password:");

        NameText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NameText.setText(Student.getProfileDetails(1, LoginSession.StudentID, "Student Records.txt")
        );
        NameText.setToolTipText("");

        GenderLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(0, 0, 0));
        GenderLabel.setText("Gender:");

        GenderCombo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        GenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderCombo.setSelectedItem(Student.getProfileDetails(4, LoginSession.StudentID, "Student Records.txt")
        );
        GenderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboActionPerformed(evt);
            }
        });

        AgeSpinner.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        AgeSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        AgeSpinner.setValue(Integer.parseInt(Student.getProfileDetails(3, LoginSession.StudentID, "Student Records.txt"))
        );

        ModifyButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ModifyButton.setText("Modify");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        PasswordText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        PasswordText.setText(Student.getProfileDetails(1, LoginSession.Username, "Username & Password.txt")
        );
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(158, Short.MAX_VALUE)
                        .addComponent(ModifyProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModifyButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GenderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenderCombo, 0, 150, Short.MAX_VALUE)
                            .addComponent(PasswordText))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(ModifyProfileLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(ModifyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderComboActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        StudentModifySelfRecord mp = new StudentModifySelfRecord();
        mp.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        Student s = new Student();
        if (NameText.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty name entered!", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        s.name = NameText.getText().trim();
        s.age = (Integer) AgeSpinner.getValue();
        s.gender = GenderCombo.getSelectedItem().toString();
        if (PasswordText.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Empty password entered!", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        s.password = PasswordText.getText().trim();
        int result = s.modifyProfile();
        switch (result) {
            case -1:
                JOptionPane.showMessageDialog(this, "Error opening file to modify!", "Error Message", JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                JOptionPane.showMessageDialog(this, "Modification successful!", "Congratualations", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentModifyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentModifyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JSpinner AgeSpinner;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> GenderCombo;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel ModifyProfileLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordText;
    // End of variables declaration//GEN-END:variables
}
