/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author System Manager
 */
public class StudentViewDetails extends javax.swing.JFrame {

    /**
     * Creates new form StudentViewDetails
     */
    public StudentViewDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentViewCoach = new javax.swing.JButton();
        StudentViewSelfrecord = new javax.swing.JButton();
        StudentViewRegisteredSportSchedule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        SportButton = new javax.swing.JButton();
        SportScheduleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REAL CHAMPIONS SPORT ACADEMY SYSTEM");
        setPreferredSize(new java.awt.Dimension(680, 450));
        setSize(new java.awt.Dimension(680, 450));

        StudentViewCoach.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        StudentViewCoach.setText("Coach");
        StudentViewCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentViewCoachActionPerformed(evt);
            }
        });

        StudentViewSelfrecord.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        StudentViewSelfrecord.setText("Self-Record");
        StudentViewSelfrecord.setToolTipText("");
        StudentViewSelfrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentViewSelfrecordActionPerformed(evt);
            }
        });

        StudentViewRegisteredSportSchedule.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        StudentViewRegisteredSportSchedule.setText("Registered Sport Schedule");
        StudentViewRegisteredSportSchedule.setToolTipText("");
        StudentViewRegisteredSportSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentViewRegisteredSportScheduleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("View Details of...");

        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        SportButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SportButton.setText("Sport Record");
        SportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportButtonActionPerformed(evt);
            }
        });

        SportScheduleButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SportScheduleButton.setText("All Sport Schedule");
        SportScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportScheduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentViewCoach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentViewSelfrecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StudentViewRegisteredSportSchedule)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SportScheduleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(StudentViewCoach)
                .addGap(18, 18, 18)
                .addComponent(StudentViewSelfrecord)
                .addGap(18, 18, 18)
                .addComponent(StudentViewRegisteredSportSchedule)
                .addGap(18, 18, 18)
                .addComponent(SportButton)
                .addGap(18, 18, 18)
                .addComponent(SportScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentViewRegisteredSportScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentViewRegisteredSportScheduleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentViewRegisteredSportSchedule svrss = new StudentViewRegisteredSportSchedule();
        svrss.setVisible(true);
    }//GEN-LAST:event_StudentViewRegisteredSportScheduleActionPerformed

    private void StudentViewCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentViewCoachActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentViewCoach svc = new StudentViewCoach();
        svc.setVisible(true);
    }//GEN-LAST:event_StudentViewCoachActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentPage sp = new StudentPage();
        sp.displayUsername(LoginSession.Username);
        sp.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void StudentViewSelfrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentViewSelfrecordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentViewSelfrecord svs = new StudentViewSelfrecord();
        svs.setVisible(true);
    }//GEN-LAST:event_StudentViewSelfrecordActionPerformed

    private void SportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportButtonActionPerformed
        this.setVisible(false);
        SportRecordPage sp = new SportRecordPage();
        sp.setVisible(true);
    }//GEN-LAST:event_SportButtonActionPerformed

    private void SportScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportScheduleButtonActionPerformed
        this.setVisible(false);
        SportSchedulePage sp = new SportSchedulePage();
        sp.setVisible(true);
    }//GEN-LAST:event_SportScheduleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton SportButton;
    private javax.swing.JButton SportScheduleButton;
    private javax.swing.JButton StudentViewCoach;
    private javax.swing.JButton StudentViewRegisteredSportSchedule;
    private javax.swing.JButton StudentViewSelfrecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
