/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;

/**
 *
 * @author jerem
 */
public class StudentPage extends javax.swing.JFrame {
    /**
     * Creates new form StudentPage
     */
    public StudentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentPageLabel = new javax.swing.JLabel();
        ViewDetailsButton = new javax.swing.JButton();
        ModifySelfRecordButton = new javax.swing.JButton();
        FeedbackButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentPageLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        StudentPageLabel.setForeground(new java.awt.Color(0, 0, 0));
        StudentPageLabel.setText("Student Page");

        ViewDetailsButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ViewDetailsButton.setText("View Details");
        ViewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsButtonActionPerformed(evt);
            }
        });

        ModifySelfRecordButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ModifySelfRecordButton.setText("Modify self record");
        ModifySelfRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifySelfRecordButtonActionPerformed(evt);
            }
        });

        FeedbackButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        FeedbackButton.setText("Provide feedback and star to coach");
        FeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        WelcomeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        WelcomeLabel.setText("Welcome back, <username>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(ViewDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(ModifySelfRecordButton)
                .addGap(36, 36, 36)
                .addComponent(FeedbackButton)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(StudentPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(WelcomeLabel))
                    .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WelcomeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(StudentPageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FeedbackButton)
                    .addComponent(ModifySelfRecordButton)
                    .addComponent(ViewDetailsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void displayUsername(String username) {
        WelcomeLabel.setText("Welcome back, " + username);
    }
    
    private void ViewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsButtonActionPerformed
        this.setVisible(false);
        StudentViewDetails svd = new StudentViewDetails();
        svd.setVisible(true);
    }//GEN-LAST:event_ViewDetailsButtonActionPerformed

    private void ModifySelfRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifySelfRecordButtonActionPerformed
        this.setVisible(false);
        StudentModifySelfRecord mp = new StudentModifySelfRecord();
        mp.setVisible(true);
    }//GEN-LAST:event_ModifySelfRecordButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.setVisible(false);
        LoginPage.isLogin = 0;
        HomePage hp = new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void FeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackButtonActionPerformed
        this.setVisible(false);
        StudentFeedback fp = new StudentFeedback();
        fp.displayCoachNames();
        fp.setVisible(true);
    }//GEN-LAST:event_FeedbackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbackButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ModifySelfRecordButton;
    private javax.swing.JLabel StudentPageLabel;
    private javax.swing.JButton ViewDetailsButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
