/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsas;
import javax.swing.DefaultListModel;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jerem
 */
public class StudentSubscribeSports extends javax.swing.JFrame {

    /**
     * Creates new form SubscribeSportsPage
     */
    DefaultListModel model = new DefaultListModel();
    
    public StudentSubscribeSports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SportButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        SubscribeButton = new javax.swing.JButton();
        SwimmingButton = new javax.swing.JRadioButton();
        BadmintonButton = new javax.swing.JRadioButton();
        SportFeeLabel = new javax.swing.JLabel();
        FootballButton = new javax.swing.JRadioButton();
        SportFeeText = new javax.swing.JTextField();
        ArcheryButton = new javax.swing.JRadioButton();
        GymnasticsButton = new javax.swing.JRadioButton();
        VolleyballButton = new javax.swing.JRadioButton();
        BasketballButton = new javax.swing.JRadioButton();
        CricketButton = new javax.swing.JRadioButton();
        TennisButton = new javax.swing.JRadioButton();
        TableTennisButton = new javax.swing.JRadioButton();
        SportsLabel = new javax.swing.JLabel();
        SportScheduleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SportScheduleList = new javax.swing.JList<>(model);
        BackButton = new javax.swing.JButton();
        CheckButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Subscribe Sport Page");

        SubscribeButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SubscribeButton.setText("Subscribe");
        SubscribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubscribeButtonActionPerformed(evt);
            }
        });

        SportButtonGroup.add(SwimmingButton);
        SwimmingButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        SwimmingButton.setText("Swimming");
        SwimmingButton.setActionCommand(SwimmingButton.getText());
        SwimmingButton.setEnabled(false);
        SwimmingButton.setName(""); // NOI18N

        SportButtonGroup.add(BadmintonButton);
        BadmintonButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        BadmintonButton.setText("Badminton");
        BadmintonButton.setActionCommand(BadmintonButton.getText());
        BadmintonButton.setEnabled(false);

        SportFeeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        SportFeeLabel.setForeground(new java.awt.Color(0, 0, 0));
        SportFeeLabel.setText("Total sport fee:");

        SportButtonGroup.add(FootballButton);
        FootballButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        FootballButton.setText("Football");
        FootballButton.setActionCommand(FootballButton.getText());
        FootballButton.setEnabled(false);

        SportFeeText.setEditable(false);
        SportFeeText.setBackground(new java.awt.Color(255, 255, 255));
        SportFeeText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        SportFeeText.setForeground(new java.awt.Color(0, 0, 0));
        SportFeeText.setEnabled(false);

        SportButtonGroup.add(ArcheryButton);
        ArcheryButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ArcheryButton.setText("Archery");
        ArcheryButton.setActionCommand(ArcheryButton.getText());
        ArcheryButton.setEnabled(false);

        SportButtonGroup.add(GymnasticsButton);
        GymnasticsButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        GymnasticsButton.setText("Gymnastics");
        GymnasticsButton.setActionCommand(GymnasticsButton.getText());
        GymnasticsButton.setEnabled(false);

        SportButtonGroup.add(VolleyballButton);
        VolleyballButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        VolleyballButton.setText("Volleyball");
        VolleyballButton.setActionCommand(VolleyballButton.getText());
        VolleyballButton.setEnabled(false);

        SportButtonGroup.add(BasketballButton);
        BasketballButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        BasketballButton.setText("Basketball");
        BasketballButton.setActionCommand(BasketballButton.getText());
        BasketballButton.setEnabled(false);

        SportButtonGroup.add(CricketButton);
        CricketButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        CricketButton.setText("Cricket");
        CricketButton.setActionCommand(CricketButton.getText());
        CricketButton.setEnabled(false);

        SportButtonGroup.add(TennisButton);
        TennisButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        TennisButton.setText("Tennis");
        TennisButton.setActionCommand(TennisButton.getText());
        TennisButton.setEnabled(false);

        SportButtonGroup.add(TableTennisButton);
        TableTennisButton.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        TableTennisButton.setText("Table Tennis");
        TableTennisButton.setActionCommand(TableTennisButton.getText());
        TableTennisButton.setEnabled(false);

        SportsLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        SportsLabel.setForeground(new java.awt.Color(0, 0, 0));
        SportsLabel.setText("Sport:");

        SportScheduleLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        SportScheduleLabel.setForeground(new java.awt.Color(0, 0, 0));
        SportScheduleLabel.setText("Sport Schedule:");

        SportScheduleList.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(SportScheduleList);

        BackButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CheckButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CheckButton.setText("Check");
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SportFeeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SportScheduleLabel)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SportFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubscribeButton)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SportsLabel)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SwimmingButton)
                            .addComponent(VolleyballButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BadmintonButton)
                            .addComponent(BasketballButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FootballButton)
                                .addGap(18, 18, 18)
                                .addComponent(ArcheryButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CricketButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TennisButton)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TableTennisButton)
                            .addComponent(GymnasticsButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckButton)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SportsLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SwimmingButton)
                            .addComponent(BadmintonButton)
                            .addComponent(FootballButton)
                            .addComponent(ArcheryButton)
                            .addComponent(GymnasticsButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VolleyballButton)
                            .addComponent(BasketballButton)
                            .addComponent(CricketButton)
                            .addComponent(TennisButton)
                            .addComponent(TableTennisButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckButton)
                    .addComponent(ClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SportFeeLabel)
                            .addComponent(SportFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(SubscribeButton)
                        .addGap(27, 27, 27)
                        .addComponent(BackButton))
                    .addComponent(SportScheduleLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubscribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubscribeButtonActionPerformed
        if (SportScheduleList.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select the sport schedule(s) that you would like to subscribe!", "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<String> selectedSportScheduleIDs = new ArrayList<String>();
        String selectedSportName = SportButtonGroup.getSelection().getActionCommand();
        List<String> selectedSportSchedules = SportScheduleList.getSelectedValuesList();
        for (String sportSchedule: selectedSportSchedules) {
            selectedSportScheduleIDs.add(sportSchedule.substring(sportSchedule.indexOf("(") + 1, sportSchedule.indexOf(")")));
        }
        int result = Student.modifyRegisteredSportSchedules(selectedSportName, selectedSportScheduleIDs);
        switch(result) {
            case 0:
                JOptionPane.showMessageDialog(this, "Subscription process completed!", "Congratualations", JOptionPane.ERROR_MESSAGE);
                break;
            case -1:
                JOptionPane.showMessageDialog(this, "Error writing into file!", "Error Message", JOptionPane.ERROR_MESSAGE);
                break;
        }
        int sportFee = selectedSportSchedules.size() * 150;
        SportFeeText.setText("RM" + sportFee);
    }//GEN-LAST:event_SubscribeButtonActionPerformed
    
    public void displaySports() {
        List<String> SportNames = Student.getSportList();
        for (String sportName: SportNames) {
            switch(sportName) {
                case "Swimming":
                    SwimmingButton.setEnabled(true);
                    break;
                case "Badminton":
                    BadmintonButton.setEnabled(true);
                    break;
                case "Football":
                    FootballButton.setEnabled(true);
                    break;
                case "Archery":
                    ArcheryButton.setEnabled(true);
                    break;
                case "Gymnastics":
                    GymnasticsButton.setEnabled(true);
                    break;
                case "Volleyball":
                    VolleyballButton.setEnabled(true);
                    break;
                case "Basketball":
                    BasketballButton.setEnabled(true);
                    break;
                case "Cricket":
                    CricketButton.setEnabled(true);
                    break;
                case "Tennis":
                    TennisButton.setEnabled(true);
                    break;
                case "Table Tennis":
                    TableTennisButton.setEnabled(true);
                    break;
            }
        }
    }
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        StudentModifySelfRecord mp = new StudentModifySelfRecord();
        mp.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        try {
            model.clear();
            String selection = SportButtonGroup.getSelection().getActionCommand();
            List<String> SportScheduleList = Student.getSportScheduleList(selection);
            for (String SportSchedule: SportScheduleList) {
                model.addElement(SportSchedule);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select one of the sports!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        SportButtonGroup.clearSelection();
        model.clear();
    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSubscribeSports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSubscribeSports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSubscribeSports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSubscribeSports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSubscribeSports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ArcheryButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton BadmintonButton;
    private javax.swing.JRadioButton BasketballButton;
    private javax.swing.JButton CheckButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JRadioButton CricketButton;
    private javax.swing.JRadioButton FootballButton;
    private javax.swing.JRadioButton GymnasticsButton;
    private javax.swing.ButtonGroup SportButtonGroup;
    private javax.swing.JLabel SportFeeLabel;
    private javax.swing.JTextField SportFeeText;
    private javax.swing.JLabel SportScheduleLabel;
    private javax.swing.JList<String> SportScheduleList;
    private javax.swing.JLabel SportsLabel;
    private javax.swing.JButton SubscribeButton;
    private javax.swing.JRadioButton SwimmingButton;
    private javax.swing.JRadioButton TableTennisButton;
    private javax.swing.JRadioButton TennisButton;
    private javax.swing.JRadioButton VolleyballButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
